version: "3.8"
#Direct the main healthcheck to port 8000
services:
  health-check:
    build: .
    depends_on:
      - face-bokeh
      - face-emotion
    ports:
      - "8000:8000"
#Direct the face-bokeh to port 8001
  face-bokeh:
    build: ./face-bokeh
    ports:
      - "8001:8000"
#Direct the face-emotion to port 8002
  face-emotion:
    build: ./face-emotion
    ports:
      - "8002:8000"